cluster:
  name: dev
  artifact:
    local: "./target/debug/greptime"
  frontend:
    replicas: 1
    httpAddr: 192.168.31.53:4000
  datanode:
    replicas: 1
    rpcAddr: 0.0.0.0:14100
    mysqlAddr: 0.0.0.0:14200
    httpAddr: 0.0.0.0:14300
  meta:
    replicas: 1
    storeAddr: 127.0.0.1:2379
    serverAddr: 0.0.0.0:3002
    httpAddr: 0.0.0.0:14001

etcd:
  artifact:
    version: v3.5.7
